platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

#target "HazeMalaysia", :exclusive => true do
    pod 'SwiftyUserDefaults'
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'SwiftDate'
    pod 'EAIntroView', '~> 2.7.0'
    pod 'JDStatusBarNotification'
#end

#target "HazeMalaysiaExtension", :exclusive => true do
#    pod 'SwiftyUserDefaults'
#end
