# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.33.5"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
#    cocoapods

    # increment_build_number

    # xctool # run the tests of your app
  end
  
  desc "Snapshot"
  lane :snap do
      sh "snapshot reset_simulators"
      snapshot
  end
  
  desc "frameit"
  lane :frame do
      frameit
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    init
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    init
    deliver(force: true)
    # frameit
  end
  
  def init
    cert( team_id: "62H3MNSVEL" )
    sigh( team_id: "62H3MNSVEL" )
   # use the UDID of the newly created provisioning profile
   ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
   gym(scheme: "HazeMalaysia") # Build your app - more options available
  end
end
